website/auth.py
from flask import Blueprint,render_template,request,redirect,url_for,after_this_request
from website import db_connect,password_hash
from psycopg2 import IntegrityError
from datetime import datetime,timedelta
auth = Blueprint('auth',__name__)


@auth.route("/")
@auth.route("/<typ>",methods = ['GET','POST'])
def authenticate(typ='log'):
    if request.method == 'POST':
        conn = db_connect()
        cur = conn.cursor()
        if typ == 'log':
            mail = request.form.get("email")
            pwd = request.form.get("password")
            cur.execute("SELECT pwd,name,user_roles FROM user_auth WHERE mail = %s AND pending = '1';",(mail,))
            db_data = cur.fetchall()
            db_pwd = db_data[0][0] if db_data != [] else None
            print(db_data)
            if db_pwd:
                decrypted_pwd = password_hash.A3Decryption().startDecryption(db_pwd)
                if decrypted_pwd == pwd:
                    print(pwd)
                    print(decrypted_pwd)
                    print(mail)
                    @after_this_request
                    def after_index(response):
                        response.set_cookie("pg-username",db_data[0][1],expires=datetime.now() + timedelta(days=1))
                        response.set_cookie("user_roles",db_data[0][2],expires=datetime.now() + timedelta(days=1))
                        return response
                    return redirect(url_for('views.home'))
                else:
                    return render_template('auth.html',mgs='Wrong Credentials..',typ='log')
            else:
                return render_template('auth.html',mgs='User Not Found.',typ='log')
        else:
            name = request.form.get("username")
            mail = request.form.get("email")
            pwd = request.form.get("password")
            confirmPwd = request.form.get("confirmPassword")
            print(name,mail,pwd,confirmPwd)
            if typ == 'reg':
                if pwd == confirmPwd:
                    try:
                        encrypted_pwd = password_hash.A3Encryption().start_encryption(pwd,mail)
                        cur.execute("INSERT INTO user_auth (name,mail,pwd) VALUES (%s,%s,%s)",(name,mail,encrypted_pwd))
                        conn.commit()
                        return redirect(url_for('auth.authenticate',typ='log'))
                    except IntegrityError as err:
                        print(err)
                        return render_template('auth.html',mgs='Already Registered',typ='reg')
                else:
                    return render_template('auth.html',mgs='Unmatched Password',typ='reg')
            elif typ == 'forgot':
                cur.execute("SELECT name FROM user_auth WHERE mail = %s",(mail,))
                data = cur.fetchall()
                db_name = data[0][0] if data != [] else None
                if db_name == name:
                    if pwd == confirmPwd:
                        cur.execute("UPDATE user_auth SET pwd = %s WHERE mail = %s;",(pwd,mail))
                        conn.commit()
                        return redirect(url_for('auth.authenticate',typ='log'))
                    else:
                        return render_template('auth.html',mgs='Unmatched Password',typ='forgot')
                else:
                    return render_template('auth.html',mgs='Invalid Credentials',typ='forgot')
    else:
        return render_template('auth.html',typ=typ,mgs=None)

@auth.route("auth/checkforget/<email>/<name>")
def checkforget(name,email):
    conn = db_connect()
    cur = conn.cursor()
    cur.execute("SELECT name FROM user_auth WHERE mail = %s;",(email,))
    db_data = cur.fetchall()
    db_name = db_data[0][0] if db_data != [] else None
    if db_name == name:
        return [1]
    else:
        return [0]

website/views.py
from flask import Blueprint,render_template,request,jsonify,url_for,redirect
from website import db_connect
from decimal import Decimal
from psycopg2.errors import ForeignKeyViolation 
from datetime import datetime

views = Blueprint('views',__name__)

@views.route("/")
def home():
    if request.cookies.get('pg-username'): 
        conn = db_connect()
        cur = conn.cursor()
        cur.execute("SELECT count(id) FROM user_auth WHERE pending = 'f';")
        noti_counts = cur.fetchall()[0][0]
        return render_template('home.html',noti_counts=noti_counts)
    return redirect(url_for('auth.authenticate',typ='log'))

@views.route("/get-graph-report/<start_dt>/<end_dt>/<bi>/<shop>")
@views.route("/get-report",methods=['GET','POST'])
def get_report(start_dt=None,end_dt=None,bi=None,shop=None):
    if request.method == 'POST' or start_dt:
        if not start_dt and not end_dt:
            start_dt = request.form.get('start-dt')
            end_dt = request.form.get('end-dt')
            bi = request.form.get('bi')
            shop = request.form.get('shop') 
        else:
            if not request.cookies.get('pg-username'): 
                return redirect(url_for('views.home'))
        where_clause = ""
        where_clause += f"AND ej.business_unit_id = '{bi}' " if bi != '0' else ""
        where_clause += f"AND ej.shop_id = '{shop}' " if shop != '0' else ""
        conn = db_connect()
        cur = conn.cursor()
        technician_where_clause = ""
        if bi != "0":
            technician_where_clause = f"AND business_unit_id = '{bi}'"
        if shop != "0":
            technician_where_clause = f"AND shop_id = '{shop}'" 
        cur.execute(f"SELECT id,name FROM technicians WHERE id != 0 {technician_where_clause} ORDER BY id;")
        technicians_ids = cur.fetchall()
        technicians_names = [tech[1] for tech in technicians_ids]
        cur.execute("SELECT id,name FROM jobType ORDER BY id;")
        job_types = cur.fetchall()
        get_job_types = {job_type[0]:job_type[1] for job_type in job_types}
        total_result = {job_type[0]:[] for job_type in job_types}
        total_result[0] = []
        if '/get-graph-report' in request.path:
            total_result = [
                ['Amount'] + list(get_job_types.values()) + ['Total',{ 'role': 'annotation'}]
            ]
        lst_data = [Decimal('0.0') for i in technicians_names]
        get_job_types[0] = 'TOTAL'
        for idx,technician_id in enumerate(technicians_ids):
            cur.execute(f"""
            SELECT jt.id AS job_type_id,
                COALESCE(SUM(
                        CASE WHEN ej.fst_pic_id = {technician_id[0]} THEN ej.fst_pic_amt ELSE 0.0 END +
                        CASE WHEN ej.sec_pic_id = {technician_id[0]} THEN ej.sec_pic_amt ELSE 0.0 END +
                        CASE WHEN ej.thrd_pic_id = {technician_id[0]} THEN ej.thrd_pic_amt ELSE 0.0 END +
                        CASE WHEN ej.frth_pic_id = {technician_id[0]} THEN ej.frth_pic_amt ELSE 0.0 END +
                        CASE WHEN ej.lst_pic_id = {technician_id[0]} THEN ej.lst_pic_amt ELSE 0.0 END
                    ), 0.0) AS total_sum
            FROM (
                SELECT id
                FROM jobtype
            ) AS jt
            CROSS JOIN (
                SELECT DISTINCT month_extracted
                FROM eachJob
            ) AS months
            LEFT JOIN (
                SELECT *
                FROM eachJob
                WHERE job_date BETWEEN '{start_dt}' AND '{end_dt}'
            ) AS ej ON jt.id = ej.job_type_id AND months.month_extracted = ej.month_extracted
            {where_clause}
            GROUP BY jt.id
            ORDER BY jt.id;""")
            datas = cur.fetchall()
            if '/get-graph-report' in request.path:
                data = [dt[1] for dt in datas]
                total_result.append([technicians_names[idx]]+data+[sum(data),str(sum(data))])
            else:
                for data in datas:
                    lst_data[idx] += data[1]
                    total_result[data[0]].append(data[1])
            shop_name = "All Shops"
            if shop != "0":
                cur.execute("SELECT name FROM shop WHERE id = %s;",(shop,))
                shop_name = cur.fetchall()[0][0]
        if '/get-graph-report' in request.path:
            return jsonify(total_result)
        else:
            total_result[0] = lst_data
    else:
        return redirect(url_for('views.home'))
    for k,v in total_result.items():
        v.insert(0,sum(v))
    return render_template('report_graph_view.html',extra_datas=[['TYPE TOTAL'] + technicians_names,get_job_types,start_dt,end_dt,shop_name,'{:,.2f}'.format(total_result[0][0])],total_result = total_result,)

@views.route("pic-report",methods=['GET','POST'])
def pic_report():
    if not request.cookies.get('pg-username'): 
        return redirect(url_for('views.home'))
    if request.method == 'POST':
        conn = db_connect()
        cur = conn.cursor()
        start_dt = request.form.get('start-dt')
        end_dt = request.form.get('end-dt')
        bi_id = request.form.get('bi')
        shop_id = request.form.get('shop')
        technician_where_clause = ""
        if bi_id != "0":
            technician_where_clause = f"AND business_unit_id = '{bi_id}'"
        if shop_id != "0":
            technician_where_clause = f"AND shop_id = '{shop_id}'"            
        where_clause = ""
        where_clause += f"AND ej.business_unit_id = '{bi_id}' " if bi_id != '0' else ""
        where_clause += f"AND ej.shop_id = '{shop_id}' " if shop_id != '0' else ""
        cur.execute("SELECT id,name FROM jobType ORDER BY id;")
        job_types = cur.fetchall()
        cur.execute(f"SELECT id,name FROM technicians WHERE id != 0  {technician_where_clause} ORDER BY id;")
        technicians_ids = cur.fetchall()
        technicians_names = [tech[1] for tech in technicians_ids]
        total_result = {}

        for idx,technician_id in enumerate(technicians_ids):
            query = f""" 
                    SELECT
                        jt.id,
                        COALESCE(SUM(
                            CASE WHEN ej.fst_pic_id = {technician_id[0]} THEN ej.fst_pic_amt ELSE 0.0 END +
                            CASE WHEN ej.sec_pic_id = {technician_id[0]} THEN ej.sec_pic_amt ELSE 0.0 END +
                            CASE WHEN ej.thrd_pic_id = {technician_id[0]} THEN ej.thrd_pic_amt ELSE 0.0 END +
                            CASE WHEN ej.frth_pic_id = {technician_id[0]} THEN ej.frth_pic_amt ELSE 0.0 END +
                            CASE WHEN ej.lst_pic_id = {technician_id[0]} THEN ej.lst_pic_amt ELSE 0.0 END
                        ), 0.0) AS total_sum,
                        COALESCE(SUM(CASE WHEN ej.fst_pic_id = {technician_id[0]} THEN ej.fst_pic_amt ELSE 0.0 END), 0.0) AS pic_1,
                        COALESCE(SUM(CASE WHEN ej.sec_pic_id = {technician_id[0]} THEN ej.sec_pic_amt ELSE 0.0 END), 0.0) AS pic_2,
                        COALESCE(SUM(CASE WHEN ej.thrd_pic_id = {technician_id[0]} THEN ej.thrd_pic_amt ELSE 0.0 END), 0.0) AS pic_3,
                        COALESCE(SUM(CASE WHEN ej.frth_pic_id = {technician_id[0]} THEN ej.frth_pic_amt ELSE 0.0 END), 0.0) AS pic_4,
                        COALESCE(SUM(CASE WHEN ej.lst_pic_id = {technician_id[0]} THEN ej.lst_pic_amt ELSE 0.0 END), 0.0) AS pic_5
                    FROM (
                        SELECT id
                        FROM jobtype
                    ) AS jt
                    CROSS JOIN (
                        SELECT DISTINCT month_extracted
                        FROM eachJob
                    ) AS months
                    LEFT JOIN (
                        SELECT *
                        FROM eachJob
                        WHERE job_date BETWEEN '{start_dt}' AND '{end_dt}'
                    ) AS ej ON jt.id = ej.job_type_id AND months.month_extracted = ej.month_extracted
                        {where_clause}
                    GROUP BY jt.id
                    ORDER BY jt.id;
                """        
            cur.execute(query)
            datas = cur.fetchall()
            result = [[] for _ in range(len(job_types))]
            for data in datas:
                for i,dt in enumerate(data[1:]):
                    result[i].append('{:,.2f}'.format(dt))
            sum_of_first_column = sum(float(value.replace(',', '')) for value in result[0])
            formatted_sum = '{:,.2f}'.format(sum_of_first_column)
            result[0].append(formatted_sum)
            result = [item for subitem in result for item in subitem]
            total_result[technicians_names[idx]] = result
            if shop_id == '0':
                shop_name = 'ALL SHOPS'
            else:
                cur.execute("SELECT name FROM shop WHERE id = %s;",(shop_id,))        
                shop_name = cur.fetchall()[0][0]
    else:
        return redirect(url_for('views.home'))
    return render_template('pic_report.html',total_result=total_result,job_types=job_types,extra_datas = [start_dt,end_dt,shop_name])


@views.route("/show-datas/<typ>/<mgs>",methods=['GET'])
@views.route("/show-datas/<typ>",methods=['GET','POST'])
def show_service_datas(typ,mgs=None):
    if not request.cookies.get('user_roles') or not request.cookies.get('pg-username'):
        return redirect(url_for('views.home'))
    mgs = request.args.get("mgs")
    conn = db_connect()
    cur = conn.cursor()
    user_roles_lst = request.cookies.get('user_roles')
    extra_datas = []
    if request.method == 'POST':
        filt = True
        column = request.form.get('column')
        db = request.form.get('database')
        val = request.form.get('filter')
        bol = request.form.get('editOrSubmit')
        print(column,'this is filter',bol)
        if typ == 'service-datas':
            if db == 'eachJob':
                query = f""" WITH month_cte AS (
                    SELECT
                        month_id,

website/templates/admin_panel.html
{% extends 'nav.html' %}

{% block title %}
Datas Tree View
{% endblock %}

{% block styles %}
<link type="text/css" rel="stylesheet" href="{{url_for('static',filename='styles/admin_panel.css')}}">
{% endblock %}

{% block innertemplate %}
<div class="account-nav-list">
    <ul>
        <li onclick="changeTab(this)" class="tab-list pending active">Pending Accounts</li>
        <li onclick="changeTab(this)" class="tab-list edit">Edit Accounts</li> 
    </ul>
</div>
<div class="account-holder" id="pendingAccount">
    <h3 class="pending-header">Pending Accounts</h3>
    {% for pending_user in pending_users %}
        <div class="pending-accounts-container">
            <div class="pending-acc">
                <div class="text-div">
                    <label>Username</label>
                    <p>{{pending_user[1]}}</p>
                </div>
                <div class="text-div">
                    <label>Email</label>
                    <p>{{pending_user[2]}}</p>
                </div>
                <div class="icon-div">
                    <i class="fa-solid fa-circle-check" onclick="checkRegisteredUser('{{pending_user[0]}}','t')"></i>
                    <i class="fa-solid fa-circle-xmark" onclick="checkRegisteredUser('{{pending_user[0]}}','del')"></i>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
<div class="account-holder" id="editAccount">
    <datalist id="shopsDataList">
        {% for data in edit_account[0].values() %}
        <option value="{{data}}">
        {% endfor %}
    </datalist>
    <h3 class="pending-header">Edit Accounts</h3>
    {% for user_data,role_data in edit_account[1].items() %}
    <div class="pending-accounts-container">
        <div class="edit-box">
            <div class="edit-acc">
                <div class="text-div">
                    <label>Username</label>
                    <p>{{user_data[0]}}</p>
                </div>
                <div class="text-div">
                    <label>Email</label>
                    <p>{{user_data[1]}}</p>
                </div>
                <div class="icon-div">
                    <i class="fa-solid fa-trash edit-icon fs-5 p-1 text-danger" onclick="checkRegisteredUser('{{user_data[2]}}','f')"></i>
                    <i class="fa-solid fa-pen-to-square edit-icon fs-5 p-1 text-secondary" onclick="editKey(this)"></i>
                </div>
            </div>
            <div class="shop-list" id="shopList">
                <input type="text" placeholder="Type Shop Name" id="shopInput" list="shopsDataList" onchange="inputShop(this,'{{user_data[1]}}')">
                <div>
                    {% for role_name in role_data %}
                    <span>{{role_name}}<i class="fa-solid fa-xmark" onclick="deleteShop(this,'{{user_data[1]}}')"></i></span>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<script type="text/javascript">
function changeTab(btn){
    const allTabs = document.querySelectorAll(".account-holder");
    const tabLists = document.querySelectorAll(".tab-list");
    const pendingAccount = document.getElementById("pendingAccount");
    if(btn.classList.contains("pending")){
        allTabs.forEach((allTab) => {
            allTab.style.display = "none";
        })
        tabLists.forEach((tabList) => {
            tabList.classList.remove("active");
        })
        pendingAccount.style.display = "block";
        btn.classList.add("active");
    }
    if(btn.classList.contains("edit")){
        allTabs.forEach((allTab) => {
            allTab.style.display = "none";
        })
        tabLists.forEach((tabList) => {
            tabList.classList.remove("active");
        })
        editAccount.style.display = "block";
        btn.classList.add("active");
    }
}

function editKey(btn){
   if(btn.parentElement.parentElement.nextElementSibling.style.display != "flex"){
    btn.parentElement.parentElement.nextElementSibling.style.display = "flex";
   }else{
    btn.parentElement.parentElement.nextElementSibling.style.display = "none";
   }
}

function inputShop(inp,mail){
    if(inp.value != ""){
        let value = inp.value;
        fetch(`/get-data/add-access/${value}|${mail}`)
        .then(response => response.json())
        .then(result => {
            if(result>0){
                let spanTag = document.createElement("span");
                spanTag.innerHTML = `${value}<i class="fa-solid fa-xmark" onclick="deleteShop(this)"></i>`;
                inp.nextElementSibling.appendChild(spanTag);
                inp.value = "";                
            }
        })
        .catch(err => console.log(err))

    }
}

function deleteShop(icon,mail){
    fetch(`/get-data/remove-access/${icon.parentElement.textContent}|${mail}`)
    .then(response => response.text())
    .then(result => {
        if(result == 'Finished'){
            icon.parentElement.remove();
        }
    })
    .catch(err => console.log(err))

}
</script>
{% endblock %}

website/templates/auth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Authentication</title>    
    <link rel="icon" type="image/x-icon" href="../static/images/web_logo.png">
    <link rel="stylesheet" href="{{url_for('static',filename='styles/auth.css')}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</head>
<body>
    <div class="main-container">
        <div class="left-side">
            <img src="{{url_for('static',filename='images/logo_opacity_3.png')}}"/>
        </div>
        <div class="right-side">
            {% if typ == 'log' %}
            <form action="{{url_for('auth.authenticate',typ='log')}}" method="post">
                <div class="inputContainer">
                    {% if mgs %}
                    <strong class="text-danger fw-bolder">{{mgs}}</strong>
                    {% endif %}
                    <div>
                        <label for="userName">Email</label>
                        <input type="email" autocomplete="off" name="email" class="userNameInput" required/>
                    </div>
                    <div>
                        <label for="userName">Password</label>
                        <input type="password" name="password" class="passwordInput" required/>
                    </div>
                    <button>Login</button>
                </div>
                <div class="signup-forget"><a href="{{url_for('auth.authenticate',typ='reg')}}">Sign Up</a> | <a href="{{url_for('auth.authenticate',typ='forget')}}">Forget Password?</a></div>
            </form>
            {% elif typ == 'reg' %}
            <!-- sign-up form -->
            <form action="{{url_for('auth.authenticate',typ='reg')}}" method="post">
                <div class="inputContainer">
                    {% if mgs %}
                    <strong class="text-danger fw-bolder">{{mgs}}</strong>
                    {% endif %}
                    <div>
                        <label for="userName">Username</label>
                        <input type="text" autocomplete="off" name="username" class="userNameInput" required/>
                    </div>
                    <div>
                        <label for="userName">Email</label>
                        <input type="email" autocomplete="off" name="email" class="userNameInput" required/>
                    </div>
                    <div>
                        <label for="userName">Password</label>
                        <input type="password" name="password" class="passwordInput" required/>
                    </div>
                    <div>
                        <label for="userName">Confirm Password</label>
                        <input type="password" name="confirmPassword" class="passwordInput" required/>
                    </div>
                    <button>Sign Up</button>
                </div>
                <div class="signup-forget"><a href="{{url_for('auth.authenticate',typ='log')}}">Login</a> | <a href="{{url_for('auth.authenticate',typ='forget')}}">Forget Password?</a></div>
            </form>
            {% else %}
            <!-- forgot password -->
            <form action="{{url_for('auth.authenticate',typ='forgot')}}" method="post">
                <div class="inputContainer">
                    {% if mgs %}
                    <strong class="text-danger fw-bolder">{{mgs}}</strong>
                    {% endif %}
                    <strong class="text-danger fw-bolder" id="forget-pwd"></strong>
                    <div>
                        <label for="userName">Email</label>
                        <input type="email" autocomplete="off" name="email" class="userNameInput" required/>
                    </div>
                    <div>
                        <label for="userName">Username</label>
                        <input type="text" autocomplete="off" name="username" class="userNameInput" required/>
                    </div>
                    <button type="button" onclick="checkUsernameForget(this)">Request Password</button>
                    <div style="display: none;">
                        <label for="userName">New Password</label>
                        <input type="password" name="password" class="passwordInput" required/>
                    </div>
                    <div style="display: none;">
                        <label for="userName">Confirm Password</label>
                        <input type="password" name="confirmPassword" class="passwordInput" required/>
                    </div>
                    <button type="submit" style="display: none;">Change Password</button>
                </div>
                <div class="signup-forget"><a href="{{url_for('auth.authenticate',typ='log')}}">Login</a> | <a href="{{url_for('auth.authenticate',typ='reg')}}">Sign Up</a></div>
            </form>
            {% endif %}
        </div>
    </div>
    <script type="text/javascript" src="{{url_for('static',filename='scripts/main.js')}}"></script>
</body>
</html>

website/templates/dashboard.html
{% extends 'nav.html' %}

{% block title %}
Dashboard
{% endblock %}

{% block styles %}
<link type="text/css" rel="stylesheet" href="{{url_for('static',filename='styles/dashboard.css')}}">
{% endblock %}

{% block innertemplate %}
<div class="dash-nav-list">
    <ul>
        <li onclick="changeTab(this)" class="tab-list psfu-call-tab active">PSFU Call</li>
        <li onclick="changeTab(this)" class="tab-list remainder-call-tab">Remainder Call</li> 
    </ul>
</div>
<form action="{{url_for('views.show_service_datas',typ='service-datas')}}" method="POST">
    <div class="search-bar d-none">
        <input type="text" hidden value="" name="column" id="column"/>
        <input type="text" placeholder="Search" class="rounded" autocomplete="off" name='filter' onkeyup="typeSthInDropdown(this)">
        <input type="text" hidden value="eachJob" name="database">
        <input hidden type="text" value="False" id="editOrSubmit" name="editOrSubmit"/>
    </div>
</form>
<div class="dashboard-holder psfu-call" id="psfuCall">
    {% for shop_name,shop_data in data_dct.items() %}
        <div class="dashboard-table">
            <table>
                <thead>
                    <tr class="main-header">
                        <th colspan="6">{{shop_name}}</th>
                    </tr>
                    <tr class="sub-header">
                        <th>Date</th>
                        <th>JOB No.</th>
                        <th>License No.</th>
                        <th>Cusomter Name</th>
                        <th>Phone No.</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% if shop_data | length == 0 %}
                        <tr class="text-center">
                            <td rowspan="5" colspan="6">No PSFU CALL Records ... </td>                          
                        </tr>
                    {% else %}
                        {% for data in shop_data %}
                        <tr onclick="redirectToFormEdit('{{data[0]}}','eachJob')">
                            <td>{{data[1]}}</td>
                            <td>{{data[0]}}</td>
                            <td>{{data[2]}}</td>
                            <td>{{data[3]}}</td>
                            <td>{{data[4]}}</td>
                            <td><input type="checkbox" value="{{data[0]}}" onclick="stopPropagation(event)" onchange="tickThePsfuCall(this)" class="line-through-check"></td>
                        </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
    {% endfor %}
</div>
<div class="dashboard-holder remainder-call" id="remainderCall">
    <h1>Remainder Call Coming Soon. . .</h1>
</div>
<script type="text/javascript">
const checkBoxs = document.querySelectorAll("tr");
checkBoxs.forEach((checkBox) => {
    checkBox.addEventListener("change", function(e){
        const tableData = checkBox.children;
        for(let i = 0; i < tableData.length; i++){
            tableData[i].classList.toggle("line-through");
        };
    })
})
function changeTab(btn){
    const allTabs = document.querySelectorAll(".dashboard-holder");
    const tabLists = document.querySelectorAll(".tab-list");
    const psfuCall = document.getElementById("psfuCall");
    const remainderCall = document.getElementById("remainderCall");
    if(btn.classList.contains("psfu-call-tab")){
        allTabs.forEach((allTab) => {
            allTab.style.display = "none";
        })
        tabLists.forEach((tabList) => {
            tabList.classList.remove("active");
        })
       psfuCall.style.display = "block";
       btn.classList.add("active");
    }
    if(btn.classList.contains("remainder-call-tab")){
        allTabs.forEach((allTab) => {
            allTab.style.display = "none";
        })
        tabLists.forEach((tabList) => {
            tabList.classList.remove("active");
        })
        remainderCall.style.display = "grid";
        btn.classList.add("active");
    }
}
</script>
{% endblock %}

website/templates/home.html
{% extends 'nav.html' %}

{% block title %}
Home
{% endblock %}

{% block styles %}
{% endblock %}

{% block innertemplate %}
<div class="home-holder">
    <img src="../static/images/pitngo-home.jpg" alt="">
</div>
{% endblock %}

{%block pendingCount %}
{{noti_counts}}
{% endblock %}